# Generated by Django 5.1 on 2024-09-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_like_timestamp_post_liked_by_alter_like_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
