# Generated by Django 5.1 on 2024-10-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_post_liked_by_post_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(default='No comments'),
            preserve_default=False,
        ),
    ]
